In [26]:
import pandas as pd
import yfinance as yf
%matplotlib inline

In [3]:
db = pd.read_pickle('prices_kr.pkl'); db

                                             close         high           low  \
2001-01-02 arirang_lowvol                      NaN          NaN           NaN
           kodex200                            NaN          NaN           NaN
           kodex_dvd_high                      NaN          NaN           NaN
           kodex_ksp                           NaN          NaN           NaN
           sec                           2625.0000    2649.0000    2461.00000
...                                            ...          ...           ...
2019-02-01 tiger_lev                    12575.0000   12805.0000   12550.00000
           tiger_lowvol                 12725.0000   12770.0000   12685.00000
           tiger_mtum                   21040.0000   21085.0000   20920.00000
           tiger_pref                    9925.0000   10015.0000    9905.00000
           tlt_ishares_us_bd_long_krw  135406.2528  136089.1051  135277.07058

                                          underlying        reprice
2001-01-02 arirang_lowvol                1000.000000    1076.985804
           kodex200                        65.410000    4917.300659
           kodex_dvd_high                1000.000000     615.595132
           kodex_ksp                      520.950000    4988.009914
           sec                                   NaN    2625.000000
...                                              ...            ...
2019-02-01 tiger_lev                    18546.315355   12575.000000
           tiger_lowvol                 12592.320000   12725.000000
           tiger_mtum                   20676.800000   21040.000000
           tiger_pref                    2436.870000    9925.000000
           tlt_ishares_us_bd_long_krw  121458.490830  135406.252800

[157686 rows x 5 columns]

In [9]:
db.unstack().close.columns.shape

(47,)

In [ ]:
def rebuild_price(prices, field):
    d = {}
    for asset in prices.index.levels[1]:
        p_ = prices[[field,'underlying']].xs(asset, level=1)
        r_ = p_.pct_change()
        p_rebuild = (r_[field].combine_first(r_.underlying).fillna(0)+1).cumprod()
        d[asset] = p_rebuild / p_rebuild[-1] * p_[field][-1]
        
    return pd.DataFrame(d)

In [24]:
p_ = db[['close','underlying']].xs('kodex200', level=1)
r_ = p_.pct_change()
p_rebuild = (r_['close'].combine_first(r_.underlying).fillna(0)+1).cumprod(); p_rebuild

2001-01-02    1.000000
2001-01-03    0.999541
2001-01-04    1.072313
2001-01-05    1.118331
2001-01-08    1.128726
                ...
2019-01-28    5.810098
2019-01-29    5.837552
2019-01-30    5.908730
2019-01-31    5.902629
2019-02-01    5.896528
Name: close, Length: 4472, dtype: float64

In [32]:
univ = pd.read_excel('etf univ.xlsx'); univ

       symbol country univ_type                    name assetclass
0   005930.KS      KR    factor                     sec     equity
1   226490.KS      KR    factor               kodex_ksp     equity
2   277630.KS      KR    factor               tiger_ksp     equity
3   069500.KS      KR    factor                kodex200     equity
4   102110.KS      KR    factor                tiger200     equity
5   122630.KS      KR    factor               kodex_lev     equity
6   123320.KS      KR    factor               tiger_lev     equity
7   123310.KS      KR    factor               tiger_inv     equity
8   244670.KS      KR    factor        kodex_value_plus     equity
9   222180.KS      KR    factor           arirang_value     equity
10  244620.KS      KR    factor         kodex_mtum_plus     equity
11  147970.KS      KR    factor              tiger_mtum     equity
12  244660.KS      KR    factor         kodex_qual_plus     equity
13  222200.KS      KR    factor            arirang_qual     equity
14  222190.KS      KR    factor            arirang_mtum     equity
15  211900.KS      KR    factor        kodex_dvd_growth     equity
16  211560.KS      KR    factor        tiger_dvd_growth     equity
17  279530.KS      KR    factor          kodex_dvd_high     equity
18  210780.KS      KR    factor      tiger_ksp_dvd_high     equity
19  266140.KS      KR    factor   tiger_dvd_sustainable     equity
20  279540.KS      KR    factor            kodex_lowvol     equity
21  174350.KS      KR    factor            tiger_lowvol     equity
22  236460.KS      KR    factor          arirang_lowvol     equity
23  217790.KS      KR    factor        tiger_contrarian     equity
24  170350.KS      KR    factor         tiger_beta_plus     equity
25  247800.KS      KR    factor        kodex_turnaround     equity
26  226980.KS      KR    factor         kodex200_midcap     equity
27  261140.KS      KR    factor              tiger_pref     equity
28  252650.KS      KR    factor             kodex200_ew     equity
29  252000.KS      KR    factor             tiger200_ew     equity
30  278420.KS      KR    factor             arirang_esg     equity
31  114260.KS      KR    factor             kodex_ktb3y       bond
32  148070.KS      KR    factor            kosef_ktb10y       bond
33  167860.KS      KR    factor        kosef_ktb10y_lev       bond
34  139260.KS      KR    sector             tiger200_it     equity
35  139270.KS      KR    sector      tiger200_financial     equity
36  139220.KS      KR    sector   tiger200_construction     equity
37  227550.KS      KR    sector     tiger200_industrial     equity
38  139230.KS      KR    sector          tiger200_heavy     equity
39  139240.KS      KR    sector       tiger200_material     equity
40  227540.KS      KR    sector     tiger200_healthcare     equity
41  139250.KS      KR    sector         tiger200_energy     equity
42  139290.KS      KR    sector  tiger200_consumer_disc     equity
43  227560.KS      KR    sector   tiger200_consumer_stp     equity

In [ ]:
symbols = ' '.join(assets.keys())
start = '2010-12-20'
end = '2020-05-08'
db = yf.download(symbols, start=start, end=end, threads=True)['Adj Close']

In [33]:
symbols = ' '.join(univ.symbol)
start = '2020-05-01'
end = '2020-05-17'
resp = yf.download(symbols, start=start, end=end, threads=True)

[*********************100%***********************]  44 of 44 completed

In [36]:
resp['Adj Close'].T

Date,2020-05-04,2020-05-06,2020-05-07,2020-05-08,2020-05-11,2020-05-12,2020-05-13,2020-05-14,2020-05-15
005930.KS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,47850.0
069500.KS,2300.0,2300.0,2250.0,2250.0,2290.0,25295.0,25585.0,25315.0,25375.0
102110.KS,25035.0,25510.0,25460.0,25675.0,25475.0,25310.0,25565.0,25310.0,25375.0
114260.KS,57750.0,57775.0,57825.0,57870.0,57865.0,57925.0,57995.0,57960.0,57970.0
122630.KS,9770.0,10100.0,10085.0,10260.0,10100.0,9960.0,10175.0,9945.0,10020.0
123310.KS,7675.0,7530.0,7550.0,7460.0,7535.0,7575.0,7500.0,7585.0,7550.0
123320.KS,9130.0,9465.0,9425.0,9590.0,9465.0,9315.0,9520.0,9325.0,9375.0
139220.KS,1845.0,1880.0,1875.0,1875.0,1855.0,1825.0,1820.0,1790.0,1815.0
139230.KS,1930.0,1990.0,1995.0,2005.0,1980.0,1930.0,1925.0,1915.0,1915.0
139240.KS,5210.0,5225.0,5265.0,5320.0,5260.0,5140.0,5115.0,5020.0,5055.0
139250.KS,9610.0,9760.0,9730.0,9730.0,9615.0,9485.0,9665.0,9500.0,9615.0
139260.KS,20470.0,20850.0,21015.0,21240.0,21175.0,21195.0,21505.0,21200.0,21210.0
139270.KS,4800.0,4820.0,4820.0,4860.0,4790.0,4700.0,4740.0,4645.0,4745.0
139290.KS,10495.0,10560.0,10570.0,10830.0,10715.0,10470.0,10515.0,10390.0,10370.0
147970.KS,15990.0,16220.0,16380.0,16610.0,16655.0,16740.0,16815.0,16935.0,17020.0
148070.KS,125545.0,125550.0,125745.0,126255.0,126155.0,126445.0,126835.0,126975.0,126950.0
167860.KS,139575.0,139520.0,140100.0,141420.0,140895.0,141730.0,142485.0,142605.0,142615.0
170350.KS,10465.0,10450.0,10460.0,10535.0,10535.0,10535.0,10535.0,10535.0,NaN
174350.KS,8940.0,9020.0,9025.0,9070.0,9055.0,8940.0,8955.0,8935.0,9025.0
210780.KS,9115.0,9205.0,9255.0,9350.0,9315.0,9160.0,9170.0,9075.0,9140.0
211560.KS,12105.0,12285.0,12340.0,12460.0,12415.0,12295.0,12400.0,12395.0,12525.0
211900.KS,9775.0,9885.0,9945.0,9990.0,10010.0,9910.0,9960.0,9940.0,10095.0
217790.KS,18050.0,18325.0,18385.0,18550.0,18385.0,18225.0,18335.0,18380.0,18490.0
222180.KS,6990.0,7025.0,7055.0,7105.0,7035.0,6960.0,7005.0,6885.0,6985.0
222190.KS,6920.0,7010.0,7070.0,7165.0,7125.0,7120.0,7175.0,7200.0,7275.0
222200.KS,7465.0,7520.0,7585.0,7670.0,7590.0,7545.0,7640.0,7565.0,7615.0
226490.KS,19060.0,19380.0,19385.0,19555.0,19455.0,19310.0,19490.0,19345.0,19385.0
226980.KS,7285.0,7385.0,7375.0,7475.0,7485.0,7420.0,7430.0,7475.0,7520.0
227540.KS,19965.0,20335.0,20210.0,20745.0,20920.0,21200.0,21415.0,21435.0,21370.0
227550.KS,3710.0,3710.0,3720.0,3770.0,3750.0,3655.0,3720.0,3685.0,3670.0
227560.KS,9990.0,10000.0,10150.0,10130.0,10050.0,10005.0,10075.0,10205.0,10250.0
236460.KS,7530.0,7580.0,7620.0,7670.0,7580.0,7535.0,7590.0,7515.0,7630.0
244620.KS,8810.0,9000.0,9130.0,9280.0,9225.0,9260.0,9305.0,9380.0,9485.0
244660.KS,7955.0,8105.0,8200.0,8275.0,8295.0,8245.0,8270.0,8205.0,8300.0
244670.KS,6145.0,6245.0,6285.0,6330.0,6320.0,6270.0,6300.0,6260.0,NaN
247800.KS,8490.0,8600.0,8685.0,8780.0,8780.0,8635.0,8575.0,8575.0,8570.0
252000.KS,7655.0,7735.0,7735.0,7735.0,7735.0,7720.0,7670.0,7745.0,7765.0
252650.KS,7555.0,7660.0,7660.0,7750.0,7740.0,7650.0,7720.0,7690.0,7755.0
261140.KS,8200.0,8245.0,8230.0,8270.0,8235.0,8150.0,8235.0,8100.0,8130.0
266140.KS,10250.0,10345.0,10385.0,10495.0,10505.0,10325.0,10330.0,10280.0,10420.0
277630.KS,19090.0,19325.0,19410.0,19540.0,19500.0,19290.0,19460.0,19310.0,19375.0
278420.KS,6665.0,6740.0,6825.0,6875.0,6860.0,6770.0,6850.0,6770.0,6865.0
279530.KS,6580.0,6655.0,6700.0,6705.0,6690.0,6605.0,6620.0,6545.0,6615.0
279540.KS,8575.0,8745.0,8765.0,8915.0,8880.0,8930.0,9020.0,9070.0,9065.0

In [37]:
yf.download('005935.KS', start=start, end=end, threads=True)

[*********************100%***********************]  1 of 1 completed

               Open     High      Low    Close  Adj Close   Volume
Date
2020-05-15  40900.0  41350.0  40700.0  40950.0    40950.0  1272336